export const ApiRouteService = {
  login: "user/login",
  logout: "user/logout",
  userSignup: "user/signup",
  userdetails: "user/userdetails",
  updateProfile: "user/update-profile",
  updateAddress: "user/update-address",
  category: "category",
  product: "product",
  customer: "customer",
  cart: "cart",
  address: "address",
  country: "country",
  state: "state",
};
